### ISSUE TITLE
ValueError in file /opt/tools/packing-box during `docker build`

### ISSUE THREAD

**Issue by RomainJennes** [packing-box/docker-packing-box#5] opened 2022-10-08 12:03 UTC
## Description

The Docker image fails to build when the command `docker build -t dhondta/packing-box .` is issued on the current version of the project. 

## Error debug output
```console
$ docker build -t dhondta/packing-box .

[...] <<snipped steps 1-32>>

Step 33/41 : RUN mv /opt/analyzers/*.zip /tmp/analyzers/  && /opt/tools/packing-box setup analyzer
 ---> Running in e073ca37c3f4
!! Could not derive your terminal width !!
Traceback (most recent call last):
  File "/opt/tools/packing-box", line 125, in <module>
    selected.remove(item.name)
ValueError: list.remove(x): x not in list
The command '/bin/sh -c mv /opt/analyzers/*.zip /tmp/analyzers/  && /opt/tools/packing-box setup analyzer' returned a non-zero code: 1
```
## Steps to reproduce
```console
$ git clone git@github.com:packing-box/docker-packing-box.git
$ cd docker-packing-box/
$ docker build -t dhondta/packing-box .
```

**Comment by dhondta** [comment] 2022-10-08 12:31
@RomainJennes Thank you for mentioning this. The issue is now fixed in the latest commit.

**Closed** 2022-10-08 12:31 UTC
